<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\spica\.DS_Store" />
    <None Include="wwwroot\spica\css\.DS_Store" />
    <None Include="wwwroot\spica\fonts\.DS_Store" />
    <None Include="wwwroot\spica\fonts\Roboto\.DS_Store" />
    <None Include="wwwroot\spica\images\.DS_Store" />
    <None Include="wwwroot\spica\images\auth\.DS_Store" />
    <None Include="wwwroot\spica\images\faces\.DS_Store" />
    <None Include="wwwroot\spica\js\.DS_Store" />
    <None Include="wwwroot\spica\pages\.DS_Store" />
    <None Include="wwwroot\spica\scss\.DS_Store" />
    <None Include="wwwroot\spica\scss\components\.DS_Store" />
    <None Include="wwwroot\spica\template\.DS_Store" />
    <None Include="wwwroot\spica\vendors\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.22" />
  </ItemGroup>

</Project>
